project:
  type: book
  output-dir: docs

book:
  title: "GF-0604 Procesamiento de datos geográficos 2026-I"
  author: "Manuel Vargas"
  date: "2026-03-09"

  chapters:
    - index.qmd
    - text: "Programa del curso - Grupo 1"
      href: gf0604-procesamientodatosgeograficos-2026-i-g001.pdf
    - text: "Programa del curso - Grupo 2"
      href: gf0604-procesamientodatosgeograficos-2026-i-g002.pdf
    - part: "I Introducción a la programación de computadoras y a la ciencia de datos"
      chapters:
        - 01-introduccion-programacion-computadoras.qmd
        - 02-introduccion-ciencia-datos.qmd
    - part: "II El lenguaje de programación R"
      chapters:
        - 03-r.qmd
    - part: "III Herramientas para investigación reproducible y desarrollo colaborativo"
      chapters:
        - 04-reproducibilidad.qmd
        - 05-markdown.qmd
        - 06-git.qmd
        - 07-quarto.qmd
    - part: "IV La colección de paquetes Tidyverse para ciencia de datos"
      chapters:
        - 08-tidyverse.qmd
        - 09-dplyr.qmd
    - part: "Tareas"
      chapters:
        - tareas/tarea-01-g001.md
        - tareas/tarea-01-g002.md
        - tareas/tarea-02-g001.md
        - tareas/tarea-02-g002.md
bibliography: referencias.bib
csl: apa-6th-edition.csl

format:
  html:
    lang: es
    theme: cosmo
    toc-expand: 5
